### ISSUE TITLE
Panic when benchmarking with target-feature=see

### ISSUE THREAD

**Issue by SuperFluffy** [bluss/matrixmultiply#29]
I wanted to check performance differences between `avx` and `sse` targets, and noticed that `sse` targets fail with a strange `index out of bounds` error:

```
% RUST_BACKTRACE=1 RUSTFLAGS="-C target-feature=sse" cargo bench ccc
    Finished release [optimized] target(s) in 0.00s
     Running target/release/deps/benchmarks-71c575834a86be6e

running 3 tests
test layout_f32_032::ccc ... thread 'main' panicked at 'index out of bounds: the len is 50 but the index is 9223372036854775808', /home/janis/.cargo/registry/src/github.com-1ecc6299db9ec823/bencher-0.1.5/stats.rs:300:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:390
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:77
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:59
   9: bencher::stats::percentile_of_sorted
  10: bencher::stats::winsorize
  11: bencher::Bencher::auto_bench
  12: bencher::run_tests_console
  13: benchmarks::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start
error: bench failed
zsh: exit 101   RUST_BACKTRACE=1 RUSTFLAGS="-C target-feature=sse" cargo bench ccc
```

This does not happen when building with `target-feature=avx`.

**Comment by bluss** [comment]
The panic is in crate bencher, and not us. We will still try to see why.

I can't reproduce the issue, so exact rust version would be good.

The syntax for target feature is "-Ctarget-feature=+sse". Can you try that?


Note that we use runtime detection and jump to an avx version automatically now, since 0.2, this is part of Rust 1.27 exciting features.

We have two cases for x86-64, avx and sse2. For testing only there are compile time environment variables to disable **runtime** checks of certain features. Run caego clean; MMNO_avx=1 cargo bench, to try that. The other one is MMNO_sse2=1

**Comment by bluss** [comment]
Thanks for reporting thw issue. Rust target would be good info too.

**Comment by bluss** [comment]
Ok, I managed to reproduce the issue on x86-64 linux. It works fine with the `+see` syntax, so I wonder what the other one is doing..

**Comment by bluss** [comment]
It looks like `target-feature=sse` has the same effect as `-sse`, i.e disabling the feature.

I see this:

```
RUSTFLAGS="-C target-feature=sse" cargo test -v
     Running `rustc --crate-name matrixmultiply src/lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=13556ee584775976 -C extra-filename=-13556ee584775976 --out-dir matrixmultiply/target/debug/deps -L dependency=matrixmultiply/target/debug/deps --extern rawpointer=matrixmultiply/target/debug/deps/librawpointer-1560524ece8c571d.rlib -C target-feature=sse`
LLVM ERROR: SSE register return with SSE disabled
error: Could not compile `bencher`.
```

I guess disabling a built-in target feature of x86-64 is not going to be supported. I think the solution is just to use the right syntax. Hope the info about runtime detection helps!

Something like this should put you on your way to test without runtime avx:

`cargo clean; MMNO_avx=1 cargo bench -v`

And, yeah, there can be positive/negative performance differences versus compiling the whole crate using different target features or not. The runtime detection only switches the microkernel's implementation.
