### ISSUE TITLE
Apple M1 SIMD support

### ISSUE THREAD

**Issue by KaedeTai** [bluss/matrixmultiply#57]
Would you please update to support Apple M1 SIMD?

**Comment by KaedeTai** [comment]
Also on Intel based Mac machines, we tested and found x64_86 flag and AVX are not enabled.

**Comment by bluss** [comment]
Hi, maybe please file and describe this as a bug report. Describe what's expected, actually happens and other relevant information, so that others understand the issue.

**Comment by bluss** [comment]
M1 SIMD support will arrive when someone contributes that. Writing a matrix multiplication kernel is highly nontrivial of course. Someone with that hardware would have to come around, to start with, too.

**Comment by bluss** [comment]
About the bug with mac intel, that should be a separate bug report? Could you get the output from this shell command in the intel mac? 

```
rustc --print cfg
```
