### ISSUE TITLE
Tiny matmul discrepancy between single- and multi- thread(?)

### ISSUE THREAD

**Issue by kstavro** [bluss/matrixmultiply#71]
There seems to be a slight discrepancy in the matmul results between using a single thread and multiple threads. At first, it felt like a rounding issue, but since I couldn't find anything relevant inside the code, I then managed to sort of replicate the results by enabling `constconf` and playing with manually setting the cache-sensitive MC, KC and NC of the sgemm/dgemm algorithm.

Can it be that single/multithreads set internally their defaults for the three constants of the algorithm differently (also differently between AMD and Intel-MKL) and hence the tiny discrepancies? Do we have an idea what the culprit of this might be?

The related issue where this was observed: https://github.com/coreylowman/dfdx/issues/560

**Comment by kstavro** [comment]
These seem to be the relevant features from the command you suggested: 
```
target_arch="x86_64"
...
target_feature="adx"
target_feature="aes"
target_feature="avx"
target_feature="avx2"
target_feature="bmi1"
target_feature="bmi2"
target_feature="f16c"
target_feature="fma"
...
```

so avx+fma in my case (AMD). And there is the Intel-mk case, which was not tested by me, though it also produced these tiny discrepancies between single and multi-thread, as in the linked issue from dfdx. An extra note is that single thread produced the exact same results with both intel-mk kernels and standard amd kernels, which led to the assumption that something might be up with multithreading.

>Would be interesting if the MATMUL_NUM_THREADS=1 variable changed results on the threading build.

This is actually where I noticed the discrepancy: `MATMUL_NUM_THREADS=1` vs `MATMUL_NUM_THREADS=4`. Or maybe I misunderstood your question and you meant if KC, NC, MC change the result with `MATMUL_NUM_THREADS=1`? To be honest, I didn't check what happens when using only one thread, all the discrepancies between different variable configs had to do with 4 threads.

Quoting from the dfdx discord (this was tested by the owner of the dfdx repo on the intel cpu once I reported the observation): 

> i'm doing a 1x2 * 2x1 matmul with matrixmultiply & naive matmul, and getting slightly different results:
> matrixmultiply: [-0.43034017]
> naive:          [-0.4303402]
> 
> it seems like a rounding issue, but i also don't see this mismatch when not using the threaded-cpu feature

The threaded-cpu feature basically activates all threads for matrixmultiply. So, it should be easy to replicate, I need to postpone it for tomorrow though (not at my pc atm). In any case, the MC, KC, NC parameters seem to play a role in it, at least in the 4-thread case.

> Out of curiosity, digging down to the code where you call blas and/or matrixmultiply, why do you use beta=1? (See https://docs.rs/matrixmultiply/latest/matrixmultiply/fn.dgemm.html ) For most work, beta=0 is faster and just overwrites the old values in C, but using beta=1 is of course more general, but you have to remember to zero C if you want to start from zero.

This is quite interesting, I wasn't aware at all of this. Actually, I never touched beta or even knew that the default is 1. Did you look inside the dfdx code and noticed beta=1 there?

**Comment by coreylowman** [comment]
Here's an example that produces small differences for me:
```rust
fn naive<const M: usize, const N: usize, const K: usize>(
    a: [[f32; K]; M],
    b: [[f32; N]; K],
) -> [[f32; N]; M] {
    let mut c = [[0.0; N]; M];
    for i_m in 0..M {
        for i_k in 0..K {
            for i_n in 0..N {
                c[i_m][i_n] += a[i_m][i_k] * b[i_k][i_n];
            }
        }
    }
    c
}

fn main() {
    let a = [[0.712813, 0.85833144], [-2.4362438, 0.16334426]]; // (2, 2)
    let b = [[-1.2750102], [1.287171]]; // (2, 1)
    let mut c = [[0.0; 1]; 2]; // (2, 1)

    unsafe {
        matrixmultiply::sgemm(
            2, // m
            2, // k
            1, // n
            1.0,
            a[0].as_ptr(),
            2, // rsa
            1, // csa
            b[0].as_ptr(),
            1, // rsb
            1, // csb
            0.0,
            c[0].as_mut_ptr(),
            1, // rsc
            1, // csc
        )
    };
    println!("matrixmultiply: {:?}", c);
    println!("naive:          {:?}", naive(a, b));
}
```

Which when using `default-features = false`, prints:
```rust
matrixmultiply: [[0.19597542], [3.3164878]]
naive:          [[0.19597542], [3.3164878]]
```

When using `default-features = false, features = ["threading"]` prints:
```rust
matrixmultiply: [[0.19597547], [3.3164878]]
naive:          [[0.19597542], [3.3164878]]
```

**Comment by coreylowman** [comment]
And yep the beta = 1.0 is for accumulation of gradients for backward pass. Technically all the matmuls in forward pass could use beta=0.0, but I just chose to use 1.0 everywhere for simplicity.

**Comment by kstavro** [comment]
Ok, this was driving me crazy because I couldn't replicate the discrepancy, but for some reason if `default-features = false` is not set (like @coreylowman did) , I get the exact same result between `features = ["threading"]` or no features. I only get the discrepancy when I specifically set `default-features = false`.

**Comment by bluss** [comment]
I don't doubt there could be something we are missing regarding accuracy, I think matrixmultiply is a bit naive about it.

**Comment by kstavro** [comment]
@bluss thanks for the clarification! This means though that if  the `fma` kernel needs to be used because of `std` when `threading` is active, we will have these tiny inaccuracies, right?

Is it possible to `MMTEST_FEATURE=sse2` with `threading` active?

**Comment by bluss** [comment]
Sure, it seems to be unperturbed by the threading feature  (Threading shouldn't affect it, the matrix is too small to be divided.)

```text
MMTEST_FEATURE=sse2 cargo run  --example accuracytest  --features threading                                                                                                                                                                           
matrixmultiply: [[0.19597542], [3.3164878]]                                                                                                            
naive:          [[0.19597542], [3.3164878]]
```

I don't know which result is more accurate to be honest. my numpy install matches the naive one (using float32), too. For all I know fma could be more accurate, but it's best to maybe calculate it out.

The answer in double precision is:

```
array([[0.19597549],
       [3.31648769]])
```

Which suggests the fma result is slightly more accurate in the first element, both are equal but way more off in the second element?

**Comment by coreylowman** [comment]
Oooh interesting, I completely missed that in the docs, thanks!

**Comment by kstavro** [comment]
> Sure, it seems to be unperturbed by the threading feature (Threading shouldn't affect it, the matrix is too small to be divided.)
> 
> ```
> MMTEST_FEATURE=sse2 cargo run  --example accuracytest  --features threading                                                                                                                                                                           
> matrixmultiply: [[0.19597542], [3.3164878]]                                                                                                            
> naive:          [[0.19597542], [3.3164878]]
> ```
> 
> I don't know which result is more accurate to be honest. my numpy install matches the naive one (using float32), too. For all I know fma could be more accurate, but it's best to maybe calculate it out.
> 
> The numpy answer in double precision is:
> 
> ```
> array([[0.19597549],
>        [3.31648769]])
> ```
> 
> Which suggests the fma result is slightly more accurate in the first element, both are equal but off by much more in the second element (?)

Yeah, you are right that we have to check which one is more accurate. But it is very useful that we now know of this important detail, in the context of very deep and wide neural networks, these inaccuracies can pile up quite fast when going through the layers (more relevant for half precision though). 

Last question (no idea about speed of kernels whatsoever): do you know if there is a difference in speed between fma and sse2?

**Comment by bluss** [comment]
`fma` uses avx features and should be a lot faster, using 256-bit simd vectors rather than the 128-bit sse2 uses (our "sse2" version is small and autovectorized, not handwritten in intrinsics like the fma kernel.). Just on my laptop, it is plenty faster, testing some various matrix sizes for the f32 type in this case. You can use the gflops column for comparison.

sse2

```
$ MMTEST_FEATURE=sse2 ./benches/benchloop.py -s 64 128 512 -t f32 | xsv table
m    k    n    layout  type  average_ns  minimum_ns  median_ns  samples  gflops              nc  kc  mc  threads                                       
64   64   64   FCC     f32   18480       18037       18284      195310   28.37056277056277               0                                             
128  128  128  FCC     f32   138709      136162      136565     7810     30.2381532560973                0                                             
512  512  512  FCC     f32   8577399     8529921     8574514    310      31.295670867124173              0          
```

fma
```
$ MMTEST_FEATURE=fma ./benches/benchloop.py -s 64 128 512 -t f32 | xsv table                                          
m    k    n    layout  type  average_ns  minimum_ns  median_ns  samples  gflops             nc  kc  mc  threads                                        
64   64   64   FCC     f32   7243        7134        7246       195310   72.38547563164434              0                                              
128  128  128  FCC     f32   54059       52549       52701      39060    77.58752474148615              0                                              
512  512  512  FCC     f32   3497384     3195745     3430824    310      76.75321211511232              0
```

**Comment by bluss** [comment]
Don't assume from any particular matrix multiplication example which one is more accurate in general, I guess. I'm interested if you bring me something you think is a real accuracy problem. It seems very useful to compare with other implementations, and to compare f32 and f64 results.

**Comment by bluss** [comment]
Maybe we can close this then?

**Comment by kstavro** [comment]
@bluss possibly not the right place to ask, but since we are on the topic of matrixmultiply/threading (and if it's ok to ask): Any intuition why implementing threading for up to 4 threads and not for 8 or 16? I couldn't derive it from the code. Maybe one won't see a performance boost using more threads? Or does something that I am missing become too complicated?

**Comment by kstavro** [comment]
(and yes, feel free to close it, thanks for all the clarifications!)
