### ISSUE TITLE
Bazel: link or target filename contains space

### ISSUE THREAD

**Issue by QuentinPerez** [bluss/matrixmultiply#79]
Hi 👋 

I just ran into an issue after a bump of dep, it seems that Bazel doesn't handle paths with spaces. Would you mind replacing the spaces with an underscore or some other character?

`link or target filename contains space on line 17: '.../external/crate_index__matrixmultiply-0.3.6/spare kernels/aarch64_neon_4x4.rs`

**Comment by bluss** [comment]
Hi. We could ignore that file from the cargo crate, because it's only relevant as a misc extra.

With that said, that's a very strange restriction from a quite modern tool. Any chance you couldn't just change a script somewhere to support spaces, some missing quotes?

**Comment by QuentinPerez** [comment]
Thx for the reactivity 🙏
